name: sproc CI checks
on:
  push:
    branches: [personal/rillbert/*, main]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest]
        ruby-version: ["2.7", "3.0", "3.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run unit tests
        run: |
          bundle exec rake test
      - name: Run linter
        run: |
          bundle exec rake standard
