name: sproc CI checks

on:
  push:
    branches: [personal/rillbert/*, main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["2.7", "3.0", "3.1"]

    steps:
      # - name: Install binutils
      #   run: |
      #     sudo apt -y install binutils
      - name: Checkout sproc
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run linting
        run: |
          bundle exec rake standard
      - name: Run unit tests
        run: |
          bundle exec rake test
